"""initial schema

Revision ID: 79ffbe8aa335
Revises: 
Create Date: 2026-08-01 18:08:47.424199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ffbe8aa335'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    # sa.func.now() compiles per dialect (now() on Postgres, CURRENT_TIMESTAMP on
    # sqlite). Autogenerate emitted the literal sqlite form because it was run
    # against a scratch sqlite db; hardcoding that would produce wrong DDL on
    # Postgres, which is the only dialect this actually deploys to.
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_date', 'goal_id', 'level', name='uq_notification_step')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
